### ISSUE TITLE
configure file is missing

### ISSUE THREAD

**Issue by Tejeshwarabm** [siscof/multi2sim-4.2#1]
There is no "configure" file, how could I configure m2s-4.2 ?

**Comment by siscof** [comment]
Hi Tejeshwara,
This is my private repo if you want to get multi2sim I would recommend you go to m2s official repo (https://github.com/Multi2Sim).  Anyway, you can find some examples of config files in the folder "samples" or executing ./m2s --mem-help (if you want to get the memory configuration format). You can check ./m2s --help for more info.
